name: flutter
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Compile m4
        run: make f-m4

      - name: Compile freezed
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Linux
        working-directory: rentnerend
        run: flutter build linux

      - uses: actions/upload-artifact@v4
        with:
          name: interscore-linux
          path: rentnerend/build/linux/x64/release/bundle/

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml

      - name: Compile m4
        run: make f-m4

      - name: Codegen
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        working-directory: rentnerend
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: interscore-android
          path: rentnerend/build/app/outputs/flutter-apk/app-release.apk

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml

      - name: Install make
        run: choco install make gnuwin32-m4
        shell: powershell

      - name: Compile m4
        run: make f-m4

      - name: Codegen
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows
        working-directory: rentnerend
        run: flutter build windows --release

      - uses: actions/upload-artifact@v4
        with:
          name: interscore-windows
          path: rentnerend/build/windows/x64/runner/Release/

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml

      - name: Compile m4
        run: make f-m4

      - name: Codegen
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build web
        working-directory: rentnerend
        run: flutter build web --release

      - uses: actions/upload-artifact@v4
        with:
          name: interscore-web
          path: rentnerend/build/web/

