name: Flutter action
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Compile m4
        run: make flutter

      - name: Compile freezed
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Linux
        working-directory: rentnerend
        run: flutter build linux

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: rentnerend/build/linux/x64/release/bundle/
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: rentnerend/pubspec.yaml

      - name: Codegen
        working-directory: rentnerend
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        working-directory: rentnerend
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: rentnerend/build/app/outputs/flutter-apk/app-release.apk
